### ISSUE TITLE
Does this project support hosting apt repos?

### ISSUE THREAD

**Issue by mateodelnorte** [jenkins-x/bucketrepo#17]
Thanks!

**Comment by ccojocar** [comment]
This project is a basic replacement for Nexus, manly for jar artifacts.

**Comment by mateodelnorte** [comment]
Nexus handles apt repos, docker registries, npm registries and more.

Mind updating your Readme with the items you do support?

Thanks in advance.

**Comment by ccojocar** [comment]
I'll update the README. It makes sense. Actually it is artifcat agonising. Any tool able to GET/PUT files under the `/bucketrepo/*file` REST endpoint, it will work with bucketrepo. 

It was definitely tested with maven and helm. This means that the following artifacts are supported:
- jars 
- helm charts

**Comment by mateodelnorte** [comment]
Cheers.
