### ISSUE TITLE
bucketrepo does not work well with GCS

### ISSUE THREAD

**Issue by heroic** [jenkins-x/bucketrepo#19]
Everytime my bucketrepo pod restarts, I get an empty index.yaml

I am seeing this error in my logs:

```
{"timestamp":"2020-02-06T14:10:51Z","serviceContext":{"service":"bucketrepo","version":"1.0"},"message":"failed to update cache for /tmp/bucketrepo/charts/index.yaml: reading file from cloud storage: blob (key \"tmp/bucketrepo/charts/index.yaml\") (code=NotFound): storage: object doesn't exist","severity":"ERROR","context":{"reportLocation":{"filePath":"internal/controller.go","lineNumber":295,"functionName":"(*FileController).chartReindex"}}}
```

It appears that bucketrepo is using the "cache.BaseDir" prefix in the cloud path as well. Whereas while updating the chart it uses the path without "cache.BaseDir".

As a temporary fix, I created a gs://repos/tmp/bucketrepo/charts/index.yaml with the expected contents manually, which results in bucket repo happily working with it, and updating the gs://repos/charts/index.yaml.

I am taking a copy of gs://repos/charts/index.yaml and pasting it to gs://repos/tmp/bucketrepo/charts/index.yaml every few days for now.

**Comment by patrickleet** [comment]
I just came here to post the same thing

```
failed to update cache for /tmp/bucketrepo/charts/index.yaml: reading file from cloud storage: blob (key "tmp/bucketrepo/charts/index.yaml") (code=NotFound): storage: object doesn't exist
(*FileController).chartReindex (internal/controller.go:295)
```

This is deleting the contents of `index.yaml` and breaking all deploys

**Comment by patrickleet** [comment]
Using 

```
  cache:
    base_dir: ./
```

For `bucketrepo` seems to fix this - Seems to get it to use the previous index file when reconstructing the index.

@jstrachan

**Comment by patrickleet** [comment]
By adding it here: https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/env/bucketrepo/values.tmpl.yaml

**Comment by patrickleet** [comment]
Well, adding it there for some reason doesn't work. Still uses the default value.

Deleting the secret and recreating it from a file on your local machine fixes the problem though - not ideal for a workaround when the solution seems so close.

How come JX boot does not use the values.tmpl.yaml file as one would expect?

**Comment by patrickleet** [comment]
ah, it's `dir`, not `base_dir`.

Adding this to `env/bucketrepo/values.tmpl.yaml` fixes this:

```
  cache:
    dir: ./
```

The README says 

```
cache:
    base_dir: "/tmp/bucketrepo"
```

But looking in the values.yaml file of the chart showed my mistake.

**Comment by patrickleet** [comment]
/remove-lifecycle-stale

My workaround that has been working for a couple months seems to have stopped working after an upgrade

```
~ jx version
Version        2.1.71
Commit         0ac50e6
Build date     2020-06-17T15:36:03Z
Go version     1.13.8
Git tree state clean
```

**Comment by patrickleet** [comment]
editing the deployment to use `gcr.io/jenkinsxio/bucketrepo:0.1.38` makes it work again

**Comment by mateuszpodraza** [comment]
/remove-lifecycle stale
I believe that #41 fixes this
