### ISSUE TITLE
dockerhub image is not accessible

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/bucketrepo#2]
Trying to use the suggested command 
```
docker run -v $(pwd)/config:/config -p 8080:8080 jenkinsxio/bucketrepo -config-path=/config
```

fails with 

```
docker: Error response from daemon: pull access denied for jenkinsxio/bucketrepo, repository does not exist or may require 'docker login'.
```

**Comment by cmur2** [comment]
Either the documentation should be updated indicating that one should build the Docker image via `make docker` after running the normal `make build` or it should be uploaded.

**Comment by ccojocar** [comment]
The project is now imported in our jenkinsx build cluster and the first release wad done today. A docker image is available:

https://hub.docker.com/r/jenkinsxio/bucketrepo/tags

I need still to update a bit the docs.

**Comment by ccojocar** [comment]
The docker image and the helm chart are properly released and the REAME updated accordantly. I am going to close this issue.

**Comment by cmur2** [comment]
Thanks for your efforts!
