### ISSUE TITLE
Newest release errors with previous cache dir settings

### ISSUE THREAD

**Issue by patrickleet** [jenkins-x/bucketrepo#42]
The newest release is not backwards compatible.

Setting the following settings was required for bucketrepo to not delete all of your charts each time it started:

```
config:
  cache:
    dir: ./
```

This now results in the following error:

```
➜  ~ k logs jenkins-x-bucketrepo-7bb5944448-bzg4n
{"timestamp":"2020-10-06T14:51:14Z","message":"Configuration: http:\n  address: :8080\n  https: false\n  certificate: \"\"\n  key: \"\"\n  username: xxx\n  password: xxx\n  chartpath: charts\nstorage:\n  enabled: true\n  bucketurl: s3://repository-20200702162217040100000006\n  timeout: 5m0s\n  prefix: \"\"\ncache:\n  basedir: ./\nrepositories:\n- url: https://repo.maven.org/maven2\n  timeout: 1m0s\n  header: {}\n- url: https://repo1.maven.org/maven2\n  timeout: 1m0s\n  header: {}\n- url: https://services.gradle.org/distributions/\n  timeout: 1m0s\n  header: {}\n- url: https://plugins.gradle.org/m2/\n  timeout: 1m0s\n  header: {}\n- url: https://repo.jenkins-ci.org/public/\n  timeout: 1m0s\n  header: {}\n- url: https://repo.jenkins-ci.org/releases/\n  timeout: 1m0s\n  header: {}\n- url: https://jitpack.io/\n  timeout: 1m0s\n  header: {}\n- url: https://registry.npmjs.org/\n  timeout: 1m0s\n  header: {}\n- url: https://repo.spring.io/milestone/\n  timeout: 1m0s\n  header: {}\n- url: https://repo.spring.io/release/\n  timeout: 1m0s\n  header: {}\n- url: http://uk.maven.org/maven2/\n  timeout: 1m0s\n  header: {}\n","severity":"INFO","context":{}}
{"timestamp":"2020-10-06T14:51:14Z","serviceContext":{"service":"bucketrepo","version":"1.0"},"message":"failed to initialise controller: failed to create charts dir charts: mkdir charts: permission denied","severity":"CRITICAL","context":{"reportLocation":{"filePath":"internal/main.go","lineNumber":39,"functionName":"main"}}}
```

**Comment by mateuszpodraza** [comment]
Interesting, it's CWD is probably not set to `/home/bucketrepo/`, that'd be another thing to fix. It should be relatively easy if you want to give it a shot 🙂 

That being said, with the reindexing func not trying to download from cloud storage with the cache dir in #41, that workaround would no longer be needed and the default value of `/tmp/bucketrepo` will still work.

I don't believe this breaks backwards compatibility per se - it breaks a workaround that was needed due to a bug

**Comment by patrickleet** [comment]
First off, I appreciate you taking up the reigns to work on this project. I am reporting my experience trying to use the changes you've made. That being said, these changes do not work, and are included in automatic jx boot upgrades - many users will receive these changes and have no idea their previous configurations no longer work.

>  It should be relatively easy if you want to give it a shot 🙂

I'd rather just revert to the version that worked

> I don't believe this breaks backwards compatibility

It does though - ask me how I know

> a workaround that was needed due to a bug

I explicitly provided a relative path, now it's something that happens implicitly

> the default value of /tmp/bucketrepo will still work.

Still work? It didn't work. You mean it now works? 

I could change it by removing the value I set, but will it delete all my charts or will it clone from s3 first? I don't understand the process under the hood enough to trust it.

**Comment by mateuszpodraza** [comment]
Are you using jx2 by any chance?
The version of bucketrepo is pinned in jx3.

I admit, I didn't look at jx2 enough, and maybe just assumed that it won't auto-upgrade something that is still versioned below 1.0.0.

> I'd rather just revert to the version that worked

It's a shame, but can't you do exactly that until we can get the cwd issue sorted?

> I explicitly provided a relative path, now it's something that happens implicitly

Not quite, there's a different issue with current working directory as a result of making this run as non-root.

> Still work? It didn't work. You mean it now works?

Sorry, I meant it should then (if we merge the PR) work with cloud storage, and will not error out on permissions.

All in all, I'm sorry that my changes have caused you trouble, I'm just trying to contribute and make this work in a way it should've been working from the start.

**Comment by patrickleet** [comment]
> Are you using jx2 by any chance?

Yes, as jx3 is in alpha. For multiple clients.

> All in all, I'm sorry that my changes have caused you trouble, I'm just trying to contribute and make this work in a way it should've been working from the start.

All good - I'm fine with breaking changes - they are inevitable, but we at a minimum need to document the process to upgrade. I know for a fact I am not the only person using these previous settings.

> It's a shame, but can't you do exactly that until we can get the cwd issue sorted?

I could - would still need to be documented as that requires a change in people's dev environment settings.

Do you know the answer to the following:

> I could change it by removing the value I set, but will it delete all my charts or will it clone from s3 first?

I do have a backup but I also have a team of developers working with the system.

**Comment by mateuszpodraza** [comment]
> Yes, as jx3 is in alpha. For multiple clients.

I'm afraid I have zero experience with jx2, I went with v3 from the start.
We might need some help here going forward - @jstrachan can you recommend anyone? Or a way to have jx2 not auto-upgrade bucketrepo?

> I could - would still need to be documented as that requires a change in people's dev environment settings.

Where would be a good place to document these in your opinion? I'm open to ideas.

> Do you know the answer to the following

If you remove that setting right now, it'll remove your chart index from S3. As far as I remember, the chart tars should be fine though.
If my last PR gets merged it should now work as expected, I'll double check that.

I'd advise you to roll with a version before the first non-root change until I can get a PR to fix the cwd issue so that the workaround continues working
